Controllers/ExcelDataController.cs
using System;
using System.IO;
using System.Data;
using System.Data.OleDb;
using System.Configuration;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;

namespace EuphoriaInfotech.Controllers
{
    public class ExcelDataController : Controller
    {
        // GET: ExcelData
        [HttpGet]
        public ActionResult ExcelRecod()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ExcelRecod(HttpPostedFileBase postedFile)

        {
            string filePath = string.Empty;
            if (postedFile != null)
            {
                string path = Server.MapPath("~/Uploads/");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                filePath = path + Path.GetFileName(postedFile.FileName);
                string extension = Path.GetExtension(postedFile.FileName);
                postedFile.SaveAs(filePath);

                string conString = string.Empty;
                switch (extension)
                {
                    case ".xls": //Excel 97-03.
                        conString = ConfigurationManager.ConnectionStrings["EuphoriaDB"].ConnectionString;
                        break;
                    case ".xlsx": //Excel 07 and above.
                        conString = ConfigurationManager.ConnectionStrings["EuphoriaDB"].ConnectionString;
                        break;
                }

                DataTable dt = new DataTable();
                conString = string.Format(conString, filePath);
                using (OleDbConnection connExcel = new OleDbConnection(conString))
                {
                    using (OleDbCommand cmdExcel = new OleDbCommand())
                    {
                        using (OleDbDataAdapter odaExcel = new OleDbDataAdapter())
                        {
                            cmdExcel.Connection = connExcel;
                            //Get the name of First Sheet.
                            connExcel.Open();
                            DataTable dtExcelSchema;
                            dtExcelSchema = connExcel.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);
                            string sheetName = dtExcelSchema.Rows[0]["ExcelMatchTbl"].ToString();
                            connExcel.Close();

                            //Read Data from First Sheet.
                            connExcel.Open();
                            cmdExcel.CommandText = "SELECT * From [" + sheetName + "]";
                            odaExcel.SelectCommand = cmdExcel;
                            odaExcel.Fill(dt);
                            connExcel.Close();
                        }
                    }
                }

                conString = ConfigurationManager.ConnectionStrings["EuphoriaDB"].ConnectionString;
                using (SqlConnection con = new SqlConnection(conString))
                {
                    using (SqlBulkCopy sqlBulkCopy = new SqlBulkCopy(con))
                    {
                        //Set the database table name.
                        sqlBulkCopy.DestinationTableName = "ExcelMatchTbl";
                        //[OPTIONAL]: Map the Excel columns with that of the database table
                        sqlBulkCopy.ColumnMappings.Add("Id", "Id");
                        sqlBulkCopy.ColumnMappings.Add("Name", "Name");
                        sqlBulkCopy.ColumnMappings.Add("Address", "Address");
                        sqlBulkCopy.ColumnMappings.Add("CourseName", "CourseName");
                        con.Open();
                        sqlBulkCopy.WriteToServer(dt);
                        con.Close();
                    }
                }
            }

            return View();
        }
    }
}

Controllers/StudentDeatilController.cs
using EuphoriaInfotech.Models;
using EuphoriaInfotech.Repository;
using EuphoriaInfotech.ViewModels;
using OpenXmlPowerTools;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using static System.Net.WebRequestMethods;

namespace EuphoriaInfotech.Controllers
{
    public class StudentDeatilController : Controller
    {
        // GET: StudentDeatil
        [HttpGet]
        public ActionResult StudentDeatil()
        {
            return View();
        }


        [HttpPost]
        public ActionResult StudentDeatil(StudentDetailsVM studentDetailsVM, HttpPostedFileBase Photo)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    StudentDetailRepo studentDetailRepo = new StudentDetailRepo();
                    string fileName = string.Empty;
                    if (Photo != null && Photo.ContentLength > 0)
                    {
                        fileName = Path.GetFileName(Photo.FileName);
                        studentDetailsVM.Photo = fileName;
                    }

                    if (studentDetailRepo.AddStudent(studentDetailsVM))
                    {
                        if (Photo != null && Photo.ContentLength > 0)
                        {
                            studentDetailsVM.Photo = fileName;
                            string path = Server.MapPath("~/Uploads/" + Photo);
                            string fullpath = Path.Combine(fileName, path);
                            Photo.SaveAs(fullpath);
                            //var fileName = Path.GetFileName(Photo.FileName);
                            //var path = Path.Combine(Server.MapPath("~/Uploads/"), fileName);
                            //Photo.SaveAs(path);
                            //studentDetailsVM.Photo = fileName;
                            //studentDetailRepo.AddStudent(studentDetailsVM);
                            if (studentDetailRepo != null)
                            {
                                return RedirectToAction(nameof(StudentAllRecod));
                            }
                        }


                        ViewBag.Message = " Student Recod  Added successfully";
                        ModelState.Clear();
                    }
                }
                return View();

            }
            catch
            {
                return View();
            }
        }


        [HttpGet]
        public ActionResult StudentAllRecod()
        {

            DataTable dt = new DataTable();
            string SqlCon = ConfigurationManager.ConnectionStrings["EuphoriaDB"].ConnectionString;
            using (SqlConnection cn = new SqlConnection(SqlCon))
            {
                using (SqlCommand cmd = new SqlCommand($"select * from StudenDetails"))
                {
                    cmd.Connection = cn;
                    using (SqlDataAdapter da = new SqlDataAdapter(cmd))
                    {
                        da.Fill(dt);
                    }
                }
            }
            return View(dt);
        }

    }
}

Controllers/TransactionYearMasterController.cs
using EuphoriaInfotech.Models;
using EuphoriaInfotech.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EuphoriaInfotech.Controllers
{
    //[Authorize]
    public class TransactionYearMasterController : Controller
    {
        // GET: TransactionYearMaster
        [HttpGet]
        public ActionResult TransactionYear()
        {
            return View();
        }


        [HttpPost]
        public ActionResult TransactionYear( TransactionYearMaster transactionYearMaster)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    AccountRepo accountRepo = new AccountRepo();

                    if (accountRepo.TransactionYear(transactionYearMaster))
                    {
                        ViewBag.Message = "TransactionYear successfully";
                        ModelState.Clear();
                    }
                }
                return View();
            }
            catch
            {
                return View();
            }

           
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Euphoria Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Euphoria Application", "AccountDetail", "Account", new { area = "" }, new { @class = "navbar-brand",@type="style=background-color:Green;" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Account Detail", "AccountDetail", "Account", new { area = "" }, new { @class = "nav-link" })</li>
                    @if (Session["LoggedInUserName"] != null)
                    {
                        <li>@Html.ActionLink("Logout", "Logout", "Account", new { area = "" }, new { @class = "nav-link" })</li>
                    }
                    <li>@Html.ActionLink("TransactionYear", "TransactionYear", "TransactionYearMaster", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Student Add Details", "StudentDeatil", "StudentDeatil", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Test Excel Details", "ExcelRecod", "ExcelData", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Euphoria Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>